library(shiny)
library(shinythemes)

ui <- fluidPage(
    theme = shinytheme("sandstone"),
    titlePanel("Video Game Sales"),
    tabsetPanel(
        
        tabPanel("Project Overview",
                sidebarPanel(
                    h3(strong("Project Purpose")),
                    h4("Many groups of people may be interested in video game sales, such as the stakeholder for the video game companies listed, the customers, 
                        the companies themselves, or simply people who are interested in playing video games."),
                    h4("Our project is designed to meet the need of these groups of people."),
                    br(),
                    h3(strong("Data Source")),
                    h4("The data is taken from:", a("https://www.kaggle.com/gregorut/videogamesales", href="https://www.kaggle.com/gregorut/videogamesales")),
                    h4("This data set contains a list of video games with sales greater than 100,000 copies.
                       It was generated by a scrape of", a("vgchartz.com", href="https://www.vgchartz.com/")),
                 ),
                 
                mainPanel(
                    img(src="game.png",  align = "center")
                )
                 
        ),
        
        tabPanel("Platform Comparison",
                 sidebarPanel(
                     radioButtons("region1", label = "Select a region",
                                  choices = list("North America" = "North America",
                                                 "Europe" = "Europe",
                                                 "Japan" = "Japan",
                                                 "Other" = "Other",
                                                 "Global" = "Global")
                     )
                 ),
                 mainPanel(
                     plotOutput("platform_Chart")
                 ),
        ),
        
        
        #### HUGH
        tabPanel(
            "Genre comparision",
            
            sidebarLayout(
                sidebarPanel(
                    radioButtons("region", label = h3("Select a region"),
                                 choices = list("North America" = "NA",
                                                "Europe" = "EU",
                                                "Japan" = "JP",
                                                "Other" = "Other",
                                                "Global" = "Global"),
                                 selected = "Global"
                    ),
                    
                    hr(),
                    
                    sliderInput("period", label = h3("Select time frame"),
                                min = 1980, max = 2016, value = c(1980, 2016), sep = "")
                ),
                
                mainPanel(h4(textOutput("textChart")), plotOutput("genreChart"))
            ),
            
            br(),
            
            h4(strong("Note: dataset only contains video games with sales greater than 100,000 copies")),
        ),
        
        
        #### ERIC
        tabPanel("Publisher Comparison",
                 sidebarPanel(
                     sliderInput("nGames",
                                 "Number of Top Games",
                                 min = 5,
                                 max = 100,
                                 value = 25),
                     radioButtons("radio",
                                  "Which Market?",
                                  choices = list("North America" = "North America",
                                                 "Europe" = "Europe",
                                                 "Japan" = "Japan",
                                                 "Other" = "Other",
                                                 "Global" = "Global"),
                                 selected = "North America"),
                     sliderInput("yearRange",
                                 "Years to Select",
                                 min = 1980, 
                                 max = 2016,
                                 value = c(2010, 2015), sep="")
                 ),
                 
                 mainPanel(
                     plotOutput("publishers"),
                     br(),
                     textOutput("reactiveCaption"),
                     br(),
                     textOutput("note")
                     
                 )
        ),
        
        tabPanel("Conclusion",
                 h3(strong("About gaming platform")),
                 tags$ul(
                     tags$li(h4("From the chart, we can see that in the North American market, the xbox 360, which is owned by the
                        company Microsoft, has the highest sales over the year of 1980 to 2020, and the second place is PS2, and their 
                        sales number are really close to each other, however, the Sony play station have more platforms than microsoft.")),
                     tags$li(h4("Moreover, from a global perspective, the play station have the highest sales number among all other platforms
                        owned by other companies, such as Europe. There is an excpetion. Japan is where both Sony and Nintendo originated,
                        but from the statistical perspective, the Nintendo seems to be more favored by the people there, and the platforms by
                        micorsoft such as xbox 360 have extremely low sales over the 40 years period, expecially when comparing with the sales
                        in North America."))
                 ),
                 br(),
                 
                 h3(strong("About gaming genre")),
                 tags$ul(
                     tags$li(h4("According to our data, platform in general was the most popular genre in the pre-2000 era.
                        The Super Mario franchise seemed to be the greatest contributor to this trend. However, after 2000,
                        action is considered to be the most dominant genre globally. I think the reason for this trend is that
                        having good combat or good story-telling is appeal to a lot of people regardless of ages.")),
                     
                     tags$li(h4("One interesting thing is that even though action genre is still the most popular genre globally after 2015,
                        shooter genre follows very closely. In North America, shooter genre actually has roughly 33% more sales than 
                        action genres. The Call of Duty franchises is the biggest contributor to this trend in North America."))
                 ),
                 br(),
                 
                 h3(strong("About game publisher")),
                 tags$ul(
                     tags$li(h4("In the earliest years of the dataset, (80-83) Atari had the most 
                        sales in hit games. After 1983, Nintendo took the lead and remained
                        strong throughout the rest of the dataset. Sony gave Nintendo some
                        notable competition in the 90's and early 00's, with about half the
                        sales that Nintendo had in the same interval, with no other 
                        publisher getting close to the numbers of these top two. Sony falls 
                        oout of the top two after the mid 00's, though it still reamins a 
                        key player. In the more recent parts of the dataset 
                        Nintendo maintained its crushing dominance in Japan, while markets 
                        besides Japan saw a robust widening of the field, with Activision, 
                        Electronic Arts and Microsoft, neack and neck or with, or overtaking
                        Nintendo in various markets. In the 'Other' market, this trend 
                        started in the mid 90's, showing that the regions that the data 
                        collectors considered miscellaneous and less important were actually
                        key trend setters for the rest of the world besides Japan."))
                 ),
                 br(),
                 
                 h3(strong("Data quality")),
                 h4("We find that our data is reasonably quality and gives unbiased results.
                     We also don't find any issues with the data that can potentially harm certain
                     population groups."),
                 br(),
                 
                 h3(strong("Future idea")),
                 h4("If we were given more time, we would like to create charts that intertwined
                    the current bar chart's topics, to answer questions such as: for a developer,
                    which gerne they are most succeed in, etc.")
                 
        )
    )
)

shinyUI(ui)